version: "3.5"
services:
  cef:
    container_name: cef
    environment:
      - "TZ=America/Sao_Paulo"
    image: cef
    restart: always
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8082:80"
    networks:
      - cef-network

networks:
  cef-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.1.0/24
          gateway: 172.50.1.1